FROM python:3.6-alpine

COPY . /server
WORKDIR /server

RUN pip3 install --upgrade pip \
&& pip3 install -r req.txt \
&& wget https://github.com/GeorgeFedoseev/DeepSpeech/releases/download/1.0/DeepSpeech-ru-v1.0-tensorflow_pb_models.tar.gz \
&& tar --strip-components=1 -xzf DeepSpeech-ru-v1.0-tensorflow_pb_models.tar.gz \
&& wget https://github.com/GeorgeFedoseev/DeepSpeech/releases/download/1.0/DeepSpeech-ru-v1.0-language_model.tar.gz \
&& tar --strip-components=1 -xzf DeepSpeech-ru-v1.0-language_model.tar.gz

WORKDIR /server
CMD ["gunicorn", "-c", "gunicorn_config.cfg", "server:app"]

